project:
  type: website
  output-dir: docs

website:
  google-analytics: "G-3FN26ZGN6Q"
  title: "AsquirousSpeaks"
  favicon: favicon-32x32_vapor2.png
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/SuchitG04/
      - icon: twitter
        href: https://twitter.com/asquirous/
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
