project:
  type: website
  output-dir: docs

website:
  title: "AsquirousSpeaks"
  favicon: favicon-16x16.png
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: solar
    css: styles.css



